import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import ThemeComponent from "@/components/Theme/ThemeComponent";
import Theme from "@/components/Theme/Theme";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/*<ThemeComponent>*/}
      <Header />
        {children}
      {/*</ThemeComponent>*/}





     </body>
    </html>
  );
}
