
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import {Router} from "react-router";
import GenreBadge from "@/components/GenreBadge";
import GenderBadge from "@/components/GenreBadge";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <Header/>
      <GenderBadge/>
      {children}

     </body>
    </html>
  );
}
